// Boolean Values
// Very often, in programming, you will need a data type that can only have one of two values, like

// YES / NO
// ON / OFF
// TRUE / FALSE
// For this, JavaScript has a Boolean data type. It can only take the values true or false.


// const x = 1;
// console.log(Boolean(x));                        // true

// const y = 0;
// console.log(Boolean(y));                      // false

// console.log(Boolean(10>5));
// console.log(Boolean(10<=5));
// console.log(Boolean(10==5));
// console.log(Boolean(5==5));
// console.log(Boolean(5===5));
// console.log(Boolean(5==="5"));
// console.log(Boolean(100));
// console.log(Boolean(3.14));
// console.log(Boolean("Hello"));
// console.log(Boolean("false"));
// console.log(Boolean(-15));
// console.log(Boolean(7 + 1 + 3.14));
// console.log(Boolean(0==false));
// console.log(Boolean(1==true));

// const x = -0;
// console.log(Boolean(x));

// const y = "";
// console.log(Boolean(y));

// let x = null;
// console.log(Boolean(x));
