//  for variable 
// When to Use var, let, or const?

// 1. Always declare variables

// 2. Always use const if the value should not be changed

// 3. Always use const if the type should not be changed (Arrays and Objects)

// 4. Only use let if you can't use const

// 5. Only use var if you MUST support old browsers.


// => JavaScript identifiers are case-sensitive.
// => The "equal to" operator is written like == in JavaScript.
// => It's a good programming practice to declare all variables at the beginning of a script.




// Operators

// Types of JavaScript Operators
// There are different types of JavaScript operators:

// Arithmetic Operators     
// Assignment Operators
// Comparison Operators
// String Operators
// Logical Operators
// Bitwise Operators
// Ternary Operators
// Type Operators


// Dataatypes:-

// => When adding a number and a string, JavaScript will treat the number as a string.






