// let MyDate = new Date()
// console.log(MyDate.toLocaleDateString())

// let MyNumber = 9978875712
// console.log(typeof  MyNumber)


//*****string to number */

// let name = 'Faisal '
// let yourName = + name   
// console.log(yourName)


//*****number to String */

// let string = '45645'
// let number = 45645
// let xyz = number
// console.log(typeof xyz.toString());

/*****Date to String****/

// let myDate = new Date(15)
// console.log(typeof myDate.toLocaleString())

/*****Date to Number****/

// let myDate = new Date('15')
// console.log(typeof myDate.gate())

/**********Number to Boolean****** */

// let number = 1
// console.log(typeof number);

/******** Boolean to Number****************/

// let number =new Number(false)
// console.log(number)


