
// Example of var variable 

// var x = 10;
// var y = 20;
// var z = x + y;

// console.log(`value of z: ${z}`)

// Example of let variable 


// let x = 10;
// let y = 20;
// let z = x + y;

// console.log(`value of z: ${z}`)



// Example of const variable 


// const x = 10;
// const y = 20;
// const z = x + y;

// console.log(`value of z: ${z}`)

// Example of mix variable 


// var x = 20;
// let y = 30;
// const z = x + y;

// console.log(z);

// // or

// const price1 =  10;
// const price2 =  10;
// let total = price1 + price2;



// let person = "John Doe", carName = "Volvo", price = 200;
// console.log(typeof person);


// var carName = "Volvo";
// var carName;                 => You cannot re-declare a variable declared with let or const.This will not work:
// No answer


// let x = 5 + 6 + 8
// console.log(x);

// var y = "5" + 6 + 8
// console.log( y);


// let x = 2 + "3" + 5;
// console.log(x);


// const z = 2 + 3 + "5";
// console.log(z);


// => why is 5 number here 
// let z = "5" *( 6 + 8)         
// console.log(z);


// let x = 5;
// x++;
// let z = x;
// console.log(z);

// let x = 5;
// x--;
// let z = x;
// console.log(z);


/// Data type //


// Primitive datatypes : "string", number, Boolean: true/false, null, undefined, object {Array object, Date object and object}

// Non Primitive Datatypes: Function,  Object, Arrays 

// String:
// let name = "Faisal"
// console.log(name);

// number:
// let number = 654
// console.log(number);

// Boolean:
// let Boolean = true
// console.log(typeof Boolean);

// Array Object:
// const Array = [1,2,3,4,5,6,7]
// console.log(Array);


//  Date Object: 
// const Date1 = new Date("17-8-2024")
// console.log(Date1);

// let x = 16 + 4 + "Volvo";
// console.log(x);


// let y = "Volvo" + 16 + 4;
// console.log(y);





// let x = 5;
// let y = 9;
// let z = 7;


// console.log((x == y) + (x == z));


// let cars = ["bmw", "I1O","BREZZA"]
// console.log(cars[1]);

// const person = {firstname : "Faisal", Lastname: "Shaikh", age : 17}
// console.log(typeof person.age);


// let cars;
// console.log(cars);


// let bikes = ""

// function myvalues(a, b) {
//     return a * b
// }
// let result = myvalues(5 , 9)
// console.log(result);


// let x = parameters(5,8)
// console.log(x)
// function parameters(a,b) {
//     return a*b
// }

// function  values(d) {
//     return (54-41) * (d - 6)
// }
// const result = values(30)
// console.log(result);
